services:
    teachr_db:
        container_name: teachr_db
        image: postgres:16.1
        restart: always
        env_file: .env.docker
        ports:
            - "54321:5432"
        volumes:
            - teachr_db_data:/var/lib/postgresql/data

    teachr_db_test:
        container_name: teachr_db_test
        image: postgres:16.1
        restart: always
        env_file: .env.test.docker
        ports:
            - "54322:5432"

volumes:
    teachr_db_data:
